# Generated by Django 4.2.6 on 2023-10-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='dade_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='dade_added',
            new_name='date_added',
        ),
    ]
